version: "3.9"
services:
  api:
    build: ./api
    ports:
      - "5000:80"
    volumes:
      - api_data:/app
    restart: always

  app:
    build: ./app
    ports:
      - "3000:3000"
    depends_on:
      - api

volumes:
  api_data:
