version: "3.9"
services:
  backend:
    build: ./backend
    ports:
      - "5000:80"
    volumes:
      - backend_data:/backend
    restart: always

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  backend_data:
